services:
  nginx:
    image: ghcr.io/hanzoai/static:0.4.1
    volumes:
      - ./certs/server:/etc/nginx/certs
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8443:443"
    networks:
      - mtls

  gatus:
    image: ghcr.io/hanzoai/status:1.0.1-arm64
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./certs/client:/certs
    environment:
      - GATUS_CONFIG_PATH=/config
    networks:
      - mtls

networks:
  mtls:
