apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: liquidity

resources:
  - ../base

patches:
  - target:
      kind: PersistentVolumeClaim
      name: status-data
    patch: |
      - op: replace
        path: /spec/storageClassName
        value: standard-rwo

configMapGenerator:
  - name: status-config
    behavior: replace
    files:
      - config.yaml=../../config/liquidity.yaml
