name: benchmark
on:
  workflow_run:
    workflows: [Docker]
    branches: [main]
    types: [completed]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch, tag or SHA to checkout"
        required: true
        default: "main"
jobs:
  build:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.1
      - uses: actions/checkout@v5
        with:
          ref: "${{ github.event.inputs.ref || 'main' }}"
      - name: Benchmark
        run: go test -bench=. ./storage/store
