name: publish-custom
run-name: "${{ inputs.tag }}"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Custom tag to publish

jobs:
  docker:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/status
      tag: ${{ inputs.tag }}
    secrets: inherit
