name: publish-experimental
on: [workflow_dispatch]

jobs:
  docker:
    uses: hanzoai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/hanzoai/status
      tag: experimental
    secrets: inherit
